ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN = 1, 2, 3, 4.0, 5.0, 6, 7, 8, 9, 10
ELEVEN = TEN.+(ONE)
TWELVE = SIX.*(TWO)
THIRTEEN = SEVEN.+(THREE)
FOURTEEN = SEVEN.*(TWO)
ZERO = ONE.-(ONE)

p ZERO
p TEN
p ELEVEN
p TWELVE
p THIRTEEN
p FOURTEEN

p FOUR / FIVE
p FOUR + FIVE
